packages:
  - 'packages/*'
  - 'packages/uniku/__tests__/e2e/runtimes/cloudflare'

allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  msgpackr-extract: false
  sharp: false
  workerd: true

catalog:
  typescript: ^6.0.3
  vitest: ^4.1.10
  wrangler: ^4.107.0
  "@cloudflare/vitest-pool-workers": ^0.18.0
  "@cloudflare/workers-types": ^5.20260706.1
  hono: ^4.12.28
